[build]
dockerfilePath = "Dockerfile"
dockerBuildTarget = "api"

[deploy]
startCommand = "sh -c 'npx prisma migrate deploy && node dist/src/server.js'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
